# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f09e48e9912ba8f904f08c0c9d16a955c06abf973b50bbbb080d53e1ee414c4272c3145caa357ccb19945678c7024d2da7851846619f854c1702a64c7b8fc83a

test:
  secret_key_base: cf13b385e48fcda41b297ec26cc20d16e3e00bd23105818ac1de9ae62bdf5f4de2aaf76eb83dcfda332628dd82b7b85ef7468af4f6ba2d30ebb998f8174e1311

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
